// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uoageqrriguxatyiissl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVvYWdlcXJyaWd1eGF0eWlpc3NsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1MTk3MzEsImV4cCI6MjA2NDA5NTczMX0.KR4hDBP8C5ooEnkRAlqgnhHs-zq48O454DMh-Jjbfbo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);